- src/components/ContributorAvatars/ContributorAvatars.scss
- styles/mixins.scss
> Colors have been updated

- src/components/Toc/Toc.scss
> Fix issue with padding for Toc

- src/components/ContributorAvatars/ContributorAvatars.scss
- src/components/ContributorAvatars/ContributorAvatars.tsx
- src/components/DocPage/DocPage.scss
- src/demo/Components/DocPage/page-ru.json
- src/models/index.ts
- styles/mixins.scss
- styles/variables.scss
> Update styles for contributors

- src/components/ContributorAvatars/Avatars/Avatar.tsx
- src/components/ContributorAvatars/ContributorAvatars.scss
- src/components/ContributorAvatars/ContributorAvatars.tsx
- src/demo/Components/DocPage/page-en.json
- src/demo/Components/DocPage/page-ru.json
1. Showing cursor only on elements with links
2. Add url for user name
3. Updating tests data
4. Fixing issues with scss
> Fix issues with tooltip

- src/components/ContributorAvatars/ContributorAvatars.scss
> Fixing shadow for contributor tooltip

- src/components/TocNavPanel/TocNavPanel.scss
> Bug was fixed with navigation links

- styles/yfm.scss
> Fixing cut margin

- package-lock.json
- package.json
- src/components/Controls/Controls.tsx
- src/components/Controls/single-controls/LangControl.tsx
- src/components/DocPage/DocPage.tsx
- src/demo/Components/DocPage/index.tsx
- src/i18n/index.ts
> feat: allow to configure the lang control

- src/components/Toc/Toc.scss
- src/components/Toc/Toc.tsx
- src/components/TocItem/TocItem.scss
- src/components/TocItem/TocItem.tsx
- src/models/index.ts
Before:
After:
https://github.com/diplodoc-platform/components/assets/112015178/1a97248a-ea13-475b-a100-ebf3f4e06ef1
In toc.yml:
```
title: Партнерский API Яндекс Маркета
href: index.md
items:
- name: Введение
href: index.md
- name: Подготовка к работе
labeled: true
items:
- name: Авторизация по OAuth-токену
href: concepts/authorization.md
items:
- name: Автоматическое обновление OAuth-токена
href: concepts/how-to-use-refresh-token.md
```
> feat: add label

- CHANGELOG.md
- package-lock.json
- package.json
This reverts commit ccb23c7fc0b530b368ac20659d0ecea52a35bf80.
> Revert "chore(master): release 4.9.2 (#257)"

- src/components/SubNavigation/SubNavigation.tsx
This reverts commit d8339cd5f8f4270aaea8ce340d175453ff320691.
> Revert "fix: window causes errors in SSR (#256)"

- src/components/Toc/Toc.tsx
replace div to nav tag in Toc component
Task: https://github.com/diplodoc-platform/components/issues/217
> add <nav> for Toc component

- src/components/MiniToc/MiniToc.scss
- src/components/Scrollspy/Scrollspy.tsx
- src/components/SubNavigation/SubNavigation.scss
- src/components/navigation/SidebarContent/SidebarContent.tsx
* Fix bug when Toc with no items rendered;
* Fix bug when overflowed MiniToc didn't get the "overflowed" class, and styles were not applied
> fix: Fix corner case behaviour of MiniToc and Toc 

- .github/workflows/ci.yml
- .github/workflows/pr-visual-tests-report.yml
Add saving PR number for test reports in ci.yml.
Change URL for test reports
> Change ci files

- demo/src/Components/Notification/index.stories.tsx
https://github.com/diplodoc-platform/components/issues/346
Add Storybook Implementation Notification Component.
Implemented story controls to allow interactive manipulation of component properties: type, title, content.
> Add Notification component in storybook

- demo/src/Components/Feedback/index.stories.tsx
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru
Add Feedback component to Storybook demo
Related issue: #345
> feat: add storybook implementation for feedback component

- src/components/SocialSharingMeta/SocialSharingMeta.tsx
- src/components/SocialSharingMeta/index.ts
Added SocialSharingMeta component
> feat: add SocialSharingMeta component

- src/components/Meta/Meta.tsx
- src/components/Meta/index.ts
> feat: Add Meta component

- src/constants.ts
- src/utils/index.ts
> fix: static lang selector

- src/components/DocLayout/DocLayout.scss
- src/components/DocPage/DocPage.scss
- src/components/DocPage/DocPage.tsx
- src/components/SubNavigation/SubNavigation.scss
- src/components/SubNavigation/SubNavigation.tsx
DOCSTOOLS-3788
- Redesign title when one header (without mini top)
- Fix share button twice show on page
> fix: subnav and share button visible, restyle subnav title

- src/components/DocContentPage/DocContentPage.tsx
- src/components/DocLeadingPage/DocLeadingPage.tsx
> fix: pass fullscreen for every layout

- .github/workflows/ci.yml
> chore: setup-node@v4

- .github/workflows/update-screenshots.yml
> fix: remove required permissions from update screenshots command

- playwright/playwright-docker.sh
> fix: source to . in docker

- demo/src/Components/MiniToc/index.stories.tsx
#344
This PR introduces story for visual description of `MiniToc` component.
> Add Storybook implementation for MiniToc component

- demo/src/Components/DocPageHidden/data.ts
- demo/src/Components/DocPageHidden/index.scss
- demo/src/Components/DocPageHidden/index.stories.tsx
- demo/src/Components/DocPageHidden/page-en.json
- demo/src/Components/DocPageHidden/page-he.json
- demo/src/Components/DocPageHidden/page-ru.json
- demo/src/Components/DocPageHidden/single-page-en.json
- demo/src/Components/DocPageHidden/single-page-ru.json
- demo/src/Components/LeadingPageHidden/index.stories.tsx
- demo/src/Components/LeadingPageHidden/page.json
- src/components/Controls/Controls.tsx
- src/components/DocContentPage/DocContentPage.tsx
- src/components/DocLayout/DocLayout.tsx
- src/components/DocLeadingPage/__tests__/DocLeadingPage.spec.ts
- src/components/DocPage/DocPage.tsx
- src/components/DocPage/__tests__/DocPage.spec.ts
- src/components/Feedback/Feedback.tsx
- src/components/SubNavigation/SubNavigation.tsx
- src/components/constants.ts
- src/components/navigation/SidebarContent/SidebarContent.tsx
- src/contexts/InterfaceContext.tsx
- src/hooks/index.ts
- src/hooks/useInterface.ts
- src/index.ts
- src/models/index.ts
> fix: add yfm interface props, tests

- src/index.ts
> fix: add useInterface export

- src/components/Toc/Toc.scss
- src/components/Toc/Toc.tsx
Return href and data-router-shallow for link in Toc components
> fix(Toc): return href and data-router-shallow for link

- src/components/SubNavigation/hooks/index.ts
- src/components/SubNavigation/index.ts
export hook useHeadingIntersectionObserver
> feat: add export hook useHeadingIntersectionObserver

- demo/src/Components/DocPage/index.stories.tsx
- src/components/Controls/Controls.tsx
- src/components/Controls/single-controls/LangControl/LangControl.tsx
- src/components/DocPage/DocPage.tsx
- src/components/MobileControls/MobileControl/MobileControl.tsx
- src/components/MobileControls/MobileControlSheet/MobileControlSheet.scss
- src/components/MobileControls/MobileControlSheet/MobileControlSheet.tsx
- src/components/MobileControls/MobileControls.tsx
- src/models/index.ts
Added availableLangs parameter to disable unavailable translations
> feat: added availableLangs

- src/components/MobileControls/MobileControlSheet/MobileControlSheet.tsx
Fixed mobile language switching
> fix: fixed mobile language switching
